spring:
  application:
    name: trajectSocialCodeChallenge
  main:
    allow-bean-definition-overriding: true
  flyway:
    enabled: true
    baseline-on-migrate: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: example
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
  
server:
  port: 8080
  
client:
  bitly:
    url: https://api-ssl.bitly.com/v4
    token: 6041d27f3348ee0cefb423b6b53ae1629c5349a1