CREATE TABLE USER_PROFILE(
	ID INTEGER NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	USERNAME VARCHAR(100) NOT NULL UNIQUE,
	URL VARCHAR(255) NOT NULL,
	SHORTENED_URL VARCHAR(100) NOT NULL,
    PRIMARY KEY (ID)
)